[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/bdayvideo"
  to = "/pages/bdayvideo.html"
  status = 200

[[redirects]]
  from = "/menu-demo"
  to = "/pages/menu-demo.html"
  status = 200

[[redirects]]
  from = "/demo-admin"
  to = "/pages/demo-admin.html"
  status = 200

[[redirects]]
  from = "/admin-demo"
  to = "/demo-admin"
  status = 301
